version: 2.1
executors:
  deploy_executor:
    docker:
      - image: circleci/openjdk:8u171-jdk


jobs:
  codedeploy:
    executor: deploy_executor
    steps:
      - checkout
      - run:
          name: build artifact
          command: mvn package
      - run:
          name: install aws
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: configure aws profile
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY --profile circleci
            aws configure set aws_secret_access_key $AWS_SECRET_KEY --profile circleci
            aws configure set region $AWS_REGION --profile circleci
            aws configure set output json --profile circleci
      - run: 
          name: upload jar and appspec.yml to s3
          command: |
            aws s3 cp ~/project/target/lambdaEmail.jar s3://$CODEDEPLOY_BUCKETNAME/ --profile circleci
            aws s3 cp ~/project/appspec.yml s3://$CODEDEPLOY_BUCKETNAME/ --profile circleci
      - run:
          name: create deploy
          command: aws deploy create-deployment --application-name $CODEDEPLOY_APPNAME --s3-location bucket=$CODEDEPLOY_BUCKETNAME,key=appspec.yml --deployment-group-name $CODEDEPLOY_GROUPNAME --description "cicd deploy lambda" --profile circleci --debug

workflows:
  build-workflow:
    jobs:
      - codedeploy
            
